#!/bin/sh

# List all processes, grep-ing for a match to the input argument when
# a match is found, we use awk to extract the process id

# NB: the 'grep -v' lines filter out any process associated with this
# script, so that we don't kill ourselves

if [ $# -gt 0 ]; then  
  for i in `ps -elf | grep "$1" | grep -v killAll | grep -v grep | awk '{print $4}'`; do
      echo "killing " $i
      kill -9 $i
      if [ $? -eq 0 ]; then
  	echo "Success, " $i
      else
  	echo "Failed to kill process " $i
      fi
  
  done
else
  echo "Must supply something to kill!"
fi
