version: '3.8'

services:
  coscine:
    image: cailmdaley/coscine:${version}
    build: 
      context: .
      target:  coscine
  coscine-dev:
    image: cailmdaley/coscine:dev-${version}
    build: 
      context: .
      target:  coscine-dev
  sptlab:
    image: cailmdaley/sptlab:dev-${version}
    build: 
      context: .
      target:  sptlab
    container_name: sptlab
    ports:
      - "8888:8888"
    volumes: 
      - '/Users/cailmdaley/:/Users/cailmdaley/'
    command: "tail -f /dev/null"
    # command: "jupyter lab --ip 0.0.0.0"
