executable = /home/ndhuang/spt_code/spt3g_software/scratch/ndhuang/condor_stuff/time_checks/run_checks.sh
arguments = "$(INPUTFILE) /spt/user/ndhuang/time_check"
universe = vanilla
notification = never
error = /slow_scratch/ndhuang/condor/logs/time_check/$(cluster).err
output = /slow_scratch/ndhuang/condor/logs/time_check/$(cluster).out
log = /home/ndhuang/condor/condor.log
+WANT_RCC_ciconnect = True
+ProjectName = "spt-all"
should_transfer_files = YES
transfer_input_files=/home/ndhuang/spt_code/spt3g_software/scratch/ndhuang/condor_stuff/time_checks/frame_grabber.py,/home/ndhuang/spt_code/spt3g_software/scratch/ndhuang/condor_stuff/time_checks/check_scu_and_sys_time.py
transfer_executable = True
transfer_output_files=""
when_to_transfer_output = ON_EXIT
use_x509userproxy = True
request_memory = 2G
request_disk = 1G
request_cpus = 1
Requirements = (OpSysAndVer == "CentOS6" || OpSysAndVer == "RedHat6" || OpSysAndVer == "SL6")
queue 
